### ISSUE TITLE
after $ ./build.sh humble  apper some issues

### ISSUE THREAD

**Issue by wh-xz** [Livox-SDK/livox_ros_driver2#150]
(ross) ┌─[wh_xz@Legion-Y7000P-IRH8] - [~/wh_xz/software/livox/src/livox_ros_driver2] - [日 10月 13, 19:34]
└─[$] <git:(master)> source /opt/ros/humble/setup.sh
./build.sh humble
Working Path: /home/wh_xz/wh_xz/software/livox/src/livox_ros_driver2
ROS version is: ROS2
Starting >>> livox_ros_driver2
Starting >>> livox_sdk2
--- stderr: livox_ros_driver2                                         
/usr/include/apr-1.0
apr-1
CMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
  execute_process(/home/wh_xz/anaconda3/envs/ross/bin/python3 -m
  rosidl_adapter --package-name livox_ros_driver2 --arguments-file
  /home/wh_xz/wh_xz/software/livox/build/livox_ros_driver2/rosidl_adapter__arguments__livox_interfaces2.json
  --output-dir
  /home/wh_xz/wh_xz/software/livox/build/livox_ros_driver2/rosidl_adapter/livox_ros_driver2
  --output-file
  /home/wh_xz/wh_xz/software/livox/build/livox_ros_driver2/rosidl_adapter/livox_interfaces2.idls)
  returned error code 1:

  AttributeError processing template 'msg.idl.em'

  Traceback (most recent call last):

    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 48, in evaluate_template
      _interpreter = em.Interpreter(

  AttributeError: module 'em' has no attribute 'Interpreter'

  

  During handling of the above exception, another exception occurred:

  

  Traceback (most recent call last):

    File "/home/wh_xz/anaconda3/envs/ross/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/home/wh_xz/anaconda3/envs/ross/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 39, in convert_msg_to_idl
      expand_template('msg.idl.em', data, output_file, encoding='iso-8859-1')
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 23, in expand_template
      content = evaluate_template(template_name, data)
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 69, in evaluate_template
      _interpreter.shutdown()

  AttributeError: 'NoneType' object has no attribute 'shutdown'

Call Stack (most recent call first):
  /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:241 (rosidl_generate_interfaces)

---
Failed   <<< livox_ros_driver2 [5.05s, exited with code 1]
Aborted  <<< livox_sdk2 [7.50s]                                

Summary: 0 packages finished [7.65s]
  1 package failed: livox_ros_driver2
  1 package aborted: livox_sdk2
  2 packages had stderr output: livox_ros_driver2 livox_sdk2

what can i do to handle this issue

**Comment by aCodeDog** [comment]
pip install empy==3.3.4

**Comment by li-yongyao** [comment]
CMake Error at CMakeLists.txt:45 (find_package):
  By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one.

  Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.



what's wrong with this error
