### ISSUE TITLE
Permission denied on driver building

### ISSUE THREAD

**Issue by jenamax** [Livox-SDK/livox_ros_driver2#18]
Hello! I am trying to build livox driver under ROS Foxy for using it inside docker container. So I want to build directly by colcon build instruction. I copied the package.xml file for ROS2 and launch files. And also I build livox_sdk2 before. I get a "permission denied" error - for both livox_sdk2 and livox_ros_driver2

'''
```
Starting >>> livox_sdk2
[0.432s] ERROR:colcon.colcon_core.shell:Exception in shell extension 'sh': [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/build/livox_sdk2/colcon_command_prefix_build.sh'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 298, in get_command_environment
    return await extension.generate_command_environment(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/sh.py", line 141, in generate_command_environment
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 54, in expand_template
    with destination_path.open('w') as h:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/build/livox_sdk2/colcon_command_prefix_build.sh'

[0.433s] ERROR:colcon.colcon_cmake.task.cmake.build:Could not find a shell extension for the command environment
Failed   <<< livox_sdk2 [0.01s, exited with code 1]
[0.434s] ERROR:colcon.colcon_core.event_reactor:Exception in event handler extension 'store_result': [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/build/livox_sdk2/colcon_build.rc'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/event_reactor.py", line 78, in _notify_observers
    retval = observer(event)
  File "/usr/lib/python3/dist-packages/colcon_package_selection/package_selection/previous/event_handler.py", line 53, in __call__
    set_result(job.task_context.args.build_base, verb_name, result)
  File "/usr/lib/python3/dist-packages/colcon_package_selection/package_selection/previous/__init__.py", line 36, in set_result
    path.write_text(str(result) + '\n')
  File "/usr/lib/python3.8/pathlib.py", line 1255, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/build/livox_sdk2/colcon_build.rc'
```

```
Starting >>> livox_ros_driver2
Finished <<< livox_sdk_vendor [0.29s]                                                                                                       
[0.986s] ERROR:colcon.colcon_core.shell:Exception in shell extension 'powershell': [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/cmake_prefix_path.ps1'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 417, in create_environment_hook
    hook = extension.create_hook_prepend_value(
  File "/usr/lib/python3/dist-packages/colcon_powershell/shell/powershell.py", line 141, in create_hook_prepend_value
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 54, in expand_template
    with destination_path.open('w') as h:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/cmake_prefix_path.ps1'

[0.987s] ERROR:colcon.colcon_core.shell:Exception in shell extension 'dsv': [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/cmake_prefix_path.dsv'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 417, in create_environment_hook
    hook = extension.create_hook_prepend_value(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/dsv.py", line 74, in create_hook_prepend_value
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 54, in expand_template
    with destination_path.open('w') as h:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/cmake_prefix_path.dsv'

[0.988s] ERROR:colcon.colcon_core.shell:Exception in shell extension 'sh': [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/cmake_prefix_path.sh'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 417, in create_environment_hook
    hook = extension.create_hook_prepend_value(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/sh.py", line 120, in create_hook_prepend_value
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 54, in expand_template
    with destination_path.open('w') as h:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/cmake_prefix_path.sh'

[0.989s] ERROR:colcon.colcon_core.environment:Exception in environment extension 'cmake_prefix_path': Could not find a primary shell extension for creating an environment hook
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/environment/__init__.py", line 175, in create_environment_hooks
    hooks = extension.create_environment_hooks(prefix_path, pkg_name)
  File "/usr/lib/python3/dist-packages/colcon_cmake/environment/cmake_prefix_path.py", line 28, in create_environment_hooks
    hooks += create_environment_hook(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 436, in create_environment_hook
    raise RuntimeError(
RuntimeError: Could not find a primary shell extension for creating an environment hook

[0.992s] ERROR:colcon.colcon_core.shell:Exception in shell extension 'powershell': [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/ld_library_path_lib.ps1'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 417, in create_environment_hook
    hook = extension.create_hook_prepend_value(
  File "/usr/lib/python3/dist-packages/colcon_powershell/shell/powershell.py", line 141, in create_hook_prepend_value
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 54, in expand_template
    with destination_path.open('w') as h:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/ld_library_path_lib.ps1'

[0.992s] ERROR:colcon.colcon_core.shell:Exception in shell extension 'dsv': [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/ld_library_path_lib.dsv'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 417, in create_environment_hook
    hook = extension.create_hook_prepend_value(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/dsv.py", line 74, in create_hook_prepend_value
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 54, in expand_template
    with destination_path.open('w') as h:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/ld_library_path_lib.dsv'

[0.993s] ERROR:colcon.colcon_core.shell:Exception in shell extension 'sh': [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/ld_library_path_lib.sh'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 417, in create_environment_hook
    hook = extension.create_hook_prepend_value(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/sh.py", line 120, in create_hook_prepend_value
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 54, in expand_template
    with destination_path.open('w') as h:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/ld_library_path_lib.sh'

[0.993s] ERROR:colcon.colcon_core.environment:Exception in environment extension 'library_path': Could not find a primary shell extension for creating an environment hook
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/environment/__init__.py", line 175, in create_environment_hooks
    hooks = extension.create_environment_hooks(prefix_path, pkg_name)
  File "/usr/lib/python3/dist-packages/colcon_library_path/environment/library_path.py", line 57, in create_environment_hooks
    environment_hooks += create_environment_hook(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 436, in create_environment_hook
    raise RuntimeError(
RuntimeError: Could not find a primary shell extension for creating an environment hook

[0.997s] ERROR:colcon.colcon_core.shell:Exception in shell extension 'powershell': [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/pythonpath.ps1'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 417, in create_environment_hook
    hook = extension.create_hook_prepend_value(
  File "/usr/lib/python3/dist-packages/colcon_powershell/shell/powershell.py", line 141, in create_hook_prepend_value
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 54, in expand_template
    with destination_path.open('w') as h:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/pythonpath.ps1'

[1.002s] ERROR:colcon.colcon_core.shell:Exception in shell extension 'dsv': [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/pythonpath.dsv'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 417, in create_environment_hook
    hook = extension.create_hook_prepend_value(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/dsv.py", line 74, in create_hook_prepend_value
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 54, in expand_template
    with destination_path.open('w') as h:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/pythonpath.dsv'

[1.003s] ERROR:colcon.colcon_core.shell:Exception in shell extension 'sh': [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/pythonpath.sh'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 417, in create_environment_hook
    hook = extension.create_hook_prepend_value(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/sh.py", line 120, in create_hook_prepend_value
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 54, in expand_template
    with destination_path.open('w') as h:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/hook/pythonpath.sh'

[1.004s] ERROR:colcon.colcon_core.environment:Exception in environment extension 'pythonpath': Could not find a primary shell extension for creating an environment hook
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/environment/__init__.py", line 175, in create_environment_hooks
    hooks = extension.create_environment_hooks(prefix_path, pkg_name)
  File "/usr/lib/python3/dist-packages/colcon_core/environment/pythonpath.py", line 26, in create_environment_hooks
    hooks += shell.create_environment_hook(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 436, in create_environment_hook
    raise RuntimeError(
RuntimeError: Could not find a primary shell extension for creating an environment hook

[1.009s] ERROR:colcon.colcon_core.environment:Exception in shell extension 'dsv': [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/package.dsv'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/environment/__init__.py", line 131, in create_environment_scripts_only
    retval = extension.create_package_script(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/dsv.py", line 30, in create_package_script
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 54, in expand_template
    with destination_path.open('w') as h:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/home/sfd/projects/self-driving-worker/self-driving-system/integration_3/src/install/livox_ros_driver2/share/livox_ros_driver2/package.dsv'

--- stderr: livox_ros_driver2                                                                           
make[2]: *** No rule to make target '/usr/local/lib/liblivox_lidar_sdk_shared.so', needed by 'liblivox_ros_driver2.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:153: CMakeFiles/livox_ros_driver2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:141: all] Error 2
---
Failed   <<< livox_ros_driver2 [0.57s, exited with code 2]

```

**Comment by Livox-Infra** [comment]
hi jenamax, it's difficult to tell the error reason based on the aboved build log. Maybe something wrond when you used 'sudo' in the build script.
